# Generated by Django 5.1 on 2024-09-02 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('TECH', 'Technology'), ('EDU', 'Education'), ('ENT', 'Entertainment'), ('HEA', 'Health'), ('LIFE', 'Lifestyle')], default='LIFE', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=10000)),
                ('title', models.CharField(max_length=300)),
                ('post_type', models.CharField(choices=[('t', 'Thread'), ('p', 'Post')], max_length=1)),
                ('parent_type', models.CharField(blank=True, choices=[('t', 'Thread'), ('p', 'Post')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_posts', to='base.post')),
                ('tag', models.ManyToManyField(to='base.tag')),
                ('author', models.ForeignKey(default='Deleted user', on_delete=django.db.models.deletion.SET_DEFAULT, to='base.user')),
            ],
        ),
    ]
