# Generated by Django 5.1 on 2024-09-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_author_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='post_author',
        ),
    ]
