# Generated by Django 5.1 on 2024-09-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_author_post_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_author',
            new_name='author',
        ),
    ]
