# Generated by Django 5.1 on 2024-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=300),
        ),
    ]
